### PR TITLE
Disable circleci docker layer caching

### PR DESCRIPTION
**Pull request by adam-murray**
Disabled docker layer caching so that CI tests don't fail

### CODE REVIEW

**Comment by Aiky30** [comment]
It appears that this package has not been created with Django CMS < 4 in mind, the folowing use of the App config does not attemot any backwards compatibility, because of this I believe that the tests for 36 are redundant. https://github.com/divio/djangocms-url-manager/blob/master/djangocms_url_manager/cms_config.py#L3

We should also add new test configuration for Django 2.2 and Python 3.7 & 3.8 as this is the future setup that the packages will need to support.

**Comment by adam-murray** [comment]
@Aiky30 Would it not make sense to add the tests you mentioned under this PR (https://github.com/divio/djangocms-url-manager/pull/31 ), I can update the issue to address the comments

**Comment by Aiky30** [comment]
@FinalAngel Are you able to review and merge this change? I don't seem to have any privileges for it at all strangely. I can review on others.

@adam-murray has another PR to remove Py3.4 and Django CMS < 4: https://github.com/divio/djangocms-url-manager/pull/31

**Comment by jonathan-s** [comment]
May I suggest that you squash the commits so that there is a single commit for disabling the caching layer. 

And python 3.7 and 3.8 should work without a hitch so I would agree with adding them. Adding django 2.2 would basically depend on https://github.com/divio/django-cms/pull/6790 so if we add that right now, that should be added as allowed failure.

**Comment by Aiky30** [comment]
> May I suggest that you squash the commits so that there is a single commit for disabling the caching layer.
> 
> And python 3.7 and 3.8 should work without a hitch so I would agree with adding them. Adding django 2.2 would basically depend on [divio/django-cms#6790](https://github.com/divio/django-cms/pull/6790) so if we add that right now, that should be added as allowed failure.

I agree, I think we'll just get the tests working here first and then open more to add 2.2 etc.

**Comment by Aiky30** [comment]
@FinalAngel Can you please squash and merge this PR.

**Pull request merged**
